"""Initial migration

Revision ID: bb44c43863f2
Revises: 
Create Date: 2025-03-04 12:09:28.739454

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import os
from passlib.context import CryptContext

# revision identifiers, used by Alembic.
revision: str = 'bb44c43863f2'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

pwd_context = CryptContext(schemes=["bcrypt"], deprecated="auto")
def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
