"""smart migration

Revision ID: eec1c08bf533
Revises: 160b18f4dce3
Create Date: 2025-02-28 00:29:16.213858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eec1c08bf533'
down_revision: Union[str, None] = '160b18f4dce3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('csv_files')
    op.drop_table('csv_data')
    op.drop_table('sents')
    op.drop_table('models')
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.VARCHAR(length=50), nullable=False),
    sa.Column('password', sa.VARCHAR(), nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('models',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), nullable=False),
    sa.Column('model_architecture', sa.VARCHAR(length=50), nullable=False),
    sa.Column('final_loss', sa.FLOAT(), nullable=True),
    sa.Column('r2', sa.FLOAT(), nullable=True),
    sa.Column('model_path', sa.VARCHAR(length=100), nullable=True),
    sa.Column('bentoml_tag', sa.VARCHAR(length=50), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=False),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('csv_id', sa.INTEGER(), nullable=True),
    sa.Column('version', sa.VARCHAR(length=20), nullable=True),
    sa.Column('description', sa.VARCHAR(length=200), nullable=True),
    sa.ForeignKeyConstraint(['csv_id'], ['csv_files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('sents',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('csv_file_id', sa.INTEGER(), nullable=False),
    sa.Column('sent_date', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['csv_file_id'], ['csv_files.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('csv_data',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('sex', sa.INTEGER(), nullable=True),
    sa.Column('age', sa.INTEGER(), nullable=True),
    sa.Column('side', sa.FLOAT(), nullable=True),
    sa.Column('BW', sa.FLOAT(), nullable=True),
    sa.Column('Ht', sa.FLOAT(), nullable=True),
    sa.Column('BMI', sa.FLOAT(), nullable=True),
    sa.Column('IKDC_pre', sa.FLOAT(), nullable=True),
    sa.Column('IKDC_3_m', sa.FLOAT(), nullable=True),
    sa.Column('IKDC_6_m', sa.FLOAT(), nullable=True),
    sa.Column('IKDC_1_Y', sa.FLOAT(), nullable=True),
    sa.Column('IKDC_2_Y', sa.FLOAT(), nullable=True),
    sa.Column('Lysholm_pre', sa.FLOAT(), nullable=True),
    sa.Column('Lysholm_3_m', sa.FLOAT(), nullable=True),
    sa.Column('Lysholm_6_m', sa.FLOAT(), nullable=True),
    sa.Column('Lysholm_1_Y', sa.FLOAT(), nullable=True),
    sa.Column('Lysholm_2_Y', sa.FLOAT(), nullable=True),
    sa.Column('Pre_KL_grade', sa.FLOAT(), nullable=True),
    sa.Column('Post_KL_grade_2_Y', sa.FLOAT(), nullable=True),
    sa.Column('MM_extrusion_pre', sa.FLOAT(), nullable=True),
    sa.Column('MM_extrusion_post', sa.FLOAT(), nullable=True),
    sa.Column('MM_gap', sa.FLOAT(), nullable=True),
    sa.Column('Degenerative_meniscus', sa.FLOAT(), nullable=True),
    sa.Column('medial_femoral_condyle', sa.FLOAT(), nullable=True),
    sa.Column('medial_tibial_condyle', sa.FLOAT(), nullable=True),
    sa.Column('lateral_femoral_condyle', sa.FLOAT(), nullable=True),
    sa.Column('lateral_tibial_condyle', sa.FLOAT(), nullable=True),
    sa.Column('csv_file_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['csv_file_id'], ['csv_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('csv_files',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('last_modified_time', sa.DATETIME(), nullable=False),
    sa.Column('model_architecture', sa.VARCHAR(length=50), nullable=True),
    sa.Column('length', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
